# Generated by Django 4.2.6 on 2024-05-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_subcategoryspecs_remove_product_category_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='product.product'),
        ),
    ]
