# Generated by Django 4.2.6 on 2024-11-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[('created', 'Created'), ('paid', 'Paid'), ('on_way', 'On way'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='created'),
        ),
    ]
