# Generated by Django 4.2.6 on 2024-11-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('on_way', 'On way'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='created', max_length=10),
        ),
    ]
