# Generated by Django 4.2.6 on 2024-10-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_firebase_account',
            field=models.BooleanField(default=False),
        ),
    ]
